In [5]:
import pandas as pd

In [6]:
df_film = pd.read_csv('top_250_film.csv')

df_film

,title,original_title,genre,score,annee,public,time,langue,pays,description,acteur
0,Léon: The Professional ...,Léon ...,Action,8.5/10,1994,Tous publics avec avertissement,110min,...,France,12-year-old Mathilda is reluctantly taken in b...,"Jean Reno, Gary Oldman, Natalie Portman"
1,Back to the Future ...,Back to the Future ...,Adventure,8.5/10,1985,Tous publics,116min,English ...,United States,"Marty McFly, a 17-year-old high school student...","Michael J. Fox, Christopher Lloyd, Lea Thompson"
2,American History X ...,American History X ...,Crime,8.5/10,1998,Tous publics avec avertissement,119min,English ...,United States,A former neo-nazi skinhead tries to prevent hi...,"Edward Norton, Edward Furlong, Beverly D'Angelo"
3,The Shawshank Redemption ...,The Shawshank Redemption ...,Drama,9.3/10,1994,Tous publics avec avertissement,142min,English ...,United States,Two imprisoned men bond over a number of years...,"Tim Robbins, Morgan Freeman, Bob Gunton"
4,The Pianist ...,The Pianist ...,Biography,8.5/10,2002,Tous publics avec avertissement,150min,"English,German,Russian ...",France,A Polish Jewish musician struggles to survive ...,"Adrien Brody, Emilia Fox, Michal Zebrowski"
...,...,...,...,...,...,...,...,...,...,...,...
244,Schindler's List ...,Schindler's List ...,Biography,9.0/10,1993,Tous publics avec avertissement,195min,"English,Hebrew,German,Polish,Latin ...",United States,"In German-occupied Poland during World War II,...","Liam Neeson, Ben Kingsley, Ralph Fiennes"
245,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Fellowship of the R...,Action,8.8/10,2001,Tous publics,178min,"English,Sindarin ...",New Zealand,A meek Hobbit from the Shire and eight compani...,"Alan Howard, Noel Appleby, Sean Astin"
246,The Godfather ...,The Godfather ...,Crime,9.2/10,1972,Tous publics avec avertissement,175min,"English,Italian,Latin ...",United States,The aging patriarch of an organized crime dyna...,"Marlon Brando, Al Pacino, James Caan"
247,The Dark Knight ...,The Dark Knight ...,Action,9.0/10,2008,Tous publics,152min,"English,Mandarin ...",United States,When the menace known as the Joker wreaks havo...,"Christian Bale, Heath Ledger, Aaron Eckhart"
248,The Lord of the Rings: The Return of the King ...,The Lord of the Rings: The Return of the King ...,Action,9.0/10,2003,Tous publics,201min,"English,Quenya,Old English,Sindarin ...",New Zealand,Gandalf and Aragorn lead the World of Men agai...,"Noel Appleby, Ali Astin, Sean Astin"

In [14]:
df_film["pays           "].value_counts()

United States      152
United Kingdom      26
Japan               14
France               8
Italy                8
Germany              7
India                5
South Korea          4
Australia            3
Sweden               3
New Zealand          3
Mexico               2
Ireland              2
Argentina            2
Iran                 2
Soviet Union         2
Turkey               1
Spain                1
Canada               1
Denmark              1
Lebanon              1
Brazil               1
Name: pays           , dtype: int64

In [101]:
df_serie = pd.read_csv('top_250_serie.csv')

df_serie

,title,original_title,score,annee,public,genre,time,pays,langue,description,acteur
0,Planet Earth II,Planet Earth II,9.5/10,2016,Tous publics,Documentary,"TV Mini Series,4,h, ,58,m",United Kingdom,English,David Attenborough returns with a new wildlife...,NaN
1,The Twilight Zone,The Twilight Zone,9.1/10,1959–1964,Tous publics,Drama,"TV Series,51,m",United States,NaN,Ordinary people find themselves in extraordina...,NaN
2,Sherlock,Sherlock,9.1/10,2010–2017,14+,Crime,"TV Series,1,h, ,28,m",United Kingdom,English,A modern update finds the famous sleuth and hi...,NaN
3,Life,Life,9.1/10,2009,Tous publics,Documentary,"TV Mini Series,7,h, ,53,m",United Kingdom,English,David Attenborough's legendary BBC crew explai...,NaN
4,Fullmetal Alchemist: Brotherhood,Hagane no renkinjutsushi,9.1/10,2009–2010,14+,Animation,"TV Series,24,m",Japan,Japanese,Two brothers search for a Philosopher's Stone ...,NaN
5,The World at War,The World at War,9.2/10,1973–1974,Tous publics,Documentary,"TV Series,52,m",United Kingdom,NaN,A groundbreaking 26-part documentary series na...,NaN
6,Our Planet,Our Planet,9.3/10,2019,Tous publics,Documentary,"TV Mini Series,6,h, ,43,m",United States,English,Documentary series focusing on the breadth of ...,NaN
7,Game of Thrones,Game of Thrones,9.2/10,2011–2019,16+,Action,"TV Series,57,m",United States,English,Nine noble families fight for control over the...,NaN
8,Cosmos,Cosmos,9.3/10,1980,Tous publics,Documentary,"TV Mini Series,13,h",United States,NaN,Astronomer Carl Sagan leads us on an engaging ...,NaN
9,Chernobyl,Chernobyl,9.4/10,2019,16+,Drama,"TV Mini Series,5,h, ,30,m",United States,English,"In April 1986, an explosion at the Chernobyl n...",NaN
10,Avatar: The Last Airbender,Avatar: The Last Airbender,9.3/10,2005–2008,7+,Animation,"TV Series,23,m",United States,English,"In a war-torn world of elemental magic, a youn...",NaN
11,Rick and Morty,Rick and Morty,9.1/10,2013–,14+,Animation,"TV Series,23,m",United States,English,An animated series that follows the exploits o...,NaN
12,Band of Brothers,Band of Brothers,9.4/10,2001,16+,Drama,"TV Mini Series,9,h, ,54,m",United States,English,The story of Easy Company of the U.S. Army 101...,NaN
13,The Wire,The Wire,9.3/10,2002–2008,16+,Crime,"TV Series,59,m",United States,English,"The Baltimore drug scene, as seen through the ...",NaN
14,Cosmos: A Spacetime Odyssey,Cosmos: A Spacetime Odyssey,9.3/10,2014,Tous publics,Documentary,"TV Mini Series,9,h, ,17,m",United States,English,An exploration of our discovery of the laws of...,NaN
15,The Sopranos,The Sopranos,9.2/10,1999–2007,16+,Crime,"TV Series,55,m",United States,English,New Jersey mob boss Tony Soprano deals with pe...,NaN
16,The Last Dance,The Last Dance,9.1/10,2020,16+,Documentary,"TV Mini Series,8,h, ,11,m",United States,English,"Charting the rise of the 1990s Chicago Bulls, ...",NaN
17,Blue Planet II,Blue Planet II,9.3/10,2017–2022,Tous publics,Documentary,"TV Mini Series,6,h, ,4,m",United Kingdom,NaN,David Attenborough returns to the world's ocea...,NaN
18,Planet Earth,Planet Earth,9.4/10,2006,Tous publics,Documentary,"TV Mini Series,8,h, ,58,m",United Kingdom,English,"Emmy Award-winning, 11 episodes, five years in...",NaN
19,Breaking Bad,Breaking Bad,9.5/10,2008–2013,16+,Crime,"TV Series,49,m",United States,English,A chemistry teacher diagnosed with inoperable ...,NaN

In [80]:
df_serie['time'] = df_serie['time'].apply(lambda x : x.split(","))

df_serie

,title,original_title,score,annee,public,genre,time,pays,langue,len
0,Planet Earth II,NaN,9.5/10,2016,TV-G,Documentary,[Not time defined],United Kingdom,NaN,1
1,The Last Dance,NaN,9.1/10,2020,16+,Documentary,[Not time defined],United States,NaN,1
2,The Twilight Zone,NaN,9.1/10,1959–1964,Tous publics,Drama,[Not time defined],United States,Stars,1
3,Life,NaN,9.1/10,2009,TV-G,Documentary,[Not time defined],United Kingdom,NaN,1
4,Our Planet,NaN,9.3/10,2019,TV-G,Documentary,[Not time defined],United States,NaN,1
5,Cosmos,NaN,9.3/10,1980,Tous publics,Documentary,[Not time defined],United States,Stars,1
6,Sherlock,NaN,9.1/10,2010–2017,TV-14,Crime,[Not time defined],United Kingdom,Stars,1
7,The World at War,NaN,9.2/10,1973–1974,Tous publics,Documentary,[Not time defined],United Kingdom,NaN,1
8,Blue Planet II,NaN,9.3/10,2017–2022,TV-G,Documentary,[Not time defined],United Kingdom,NaN,1
9,Cosmos: A Spacetime Odyssey,NaN,9.3/10,2014,Tous publics,Documentary,[Not time defined],United States,NaN,1
10,The Sopranos,NaN,9.2/10,1999–2007,16+,Crime,[Not time defined],United States,Stars,1
11,The Wire,NaN,9.3/10,2002–2008,16+,Crime,[Not time defined],United States,Stars,1
12,Avatar: The Last Airbender,NaN,9.3/10,2005–2008,7+,Animation,[Not time defined],United States,Stars,1
13,Fullmetal Alchemist: Brotherhood,Hagane no renkinjutsushi,9.1/10,2009–2010,TV-14,Animation,[Not time defined],Japan,Stars,1
14,Game of Thrones,NaN,9.2/10,2011–2019,16+,Action,[Not time defined],United States,Stars,1
15,Chernobyl,NaN,9.4/10,2019,16+,Drama,[Not time defined],United States,Stars,1
16,Rick and Morty,NaN,9.1/10,2013–,TV-14,Animation,[Not time defined],United States,Stars,1
17,Band of Brothers,NaN,9.4/10,2001,16+,Drama,[Not time defined],United States,NaN,1
18,Breaking Bad,NaN,9.5/10,2008–2013,16+,Crime,[Not time defined],United States,Stars,1
19,Planet Earth,NaN,9.4/10,2006,Tous publics,Documentary,[Not time defined],United Kingdom,NaN,1

In [81]:
df_serie['len'].value_counts()

1    20
Name: len, dtype: int64

In [83]:
def time_minute (list = list):
    if len(list) == 6 :
        time_minute = str(int(list[1]) * 60 + int(list[4])) + "min"
    elif len(list) == 3 :
        time_minute = str(int(list[1])) + "min"
    else:
        time_minute = "Not time defined"
    return time_minute

In [84]:
df_serie['time'] = df_serie['time'].apply(lambda x : time_minute(x))

df_serie.sort_values(by=['score', 'annee'], ascending=False)

,title,original_title,score,annee,public,genre,time,pays,langue,len
0,Planet Earth II,NaN,9.5/10,2016,TV-G,Documentary,Not time defined,United Kingdom,NaN,1
18,Breaking Bad,NaN,9.5/10,2008–2013,16+,Crime,Not time defined,United States,Stars,1
15,Chernobyl,NaN,9.4/10,2019,16+,Drama,Not time defined,United States,Stars,1
19,Planet Earth,NaN,9.4/10,2006,Tous publics,Documentary,Not time defined,United Kingdom,NaN,1
17,Band of Brothers,NaN,9.4/10,2001,16+,Drama,Not time defined,United States,NaN,1
4,Our Planet,NaN,9.3/10,2019,TV-G,Documentary,Not time defined,United States,NaN,1
8,Blue Planet II,NaN,9.3/10,2017–2022,TV-G,Documentary,Not time defined,United Kingdom,NaN,1
9,Cosmos: A Spacetime Odyssey,NaN,9.3/10,2014,Tous publics,Documentary,Not time defined,United States,NaN,1
12,Avatar: The Last Airbender,NaN,9.3/10,2005–2008,7+,Animation,Not time defined,United States,Stars,1
11,The Wire,NaN,9.3/10,2002–2008,16+,Crime,Not time defined,United States,Stars,1
5,Cosmos,NaN,9.3/10,1980,Tous publics,Documentary,Not time defined,United States,Stars,1
14,Game of Thrones,NaN,9.2/10,2011–2019,16+,Action,Not time defined,United States,Stars,1
10,The Sopranos,NaN,9.2/10,1999–2007,16+,Crime,Not time defined,United States,Stars,1
7,The World at War,NaN,9.2/10,1973–1974,Tous publics,Documentary,Not time defined,United Kingdom,NaN,1
1,The Last Dance,NaN,9.1/10,2020,16+,Documentary,Not time defined,United States,NaN,1
16,Rick and Morty,NaN,9.1/10,2013–,TV-14,Animation,Not time defined,United States,Stars,1
6,Sherlock,NaN,9.1/10,2010–2017,TV-14,Crime,Not time defined,United Kingdom,Stars,1
13,Fullmetal Alchemist: Brotherhood,Hagane no renkinjutsushi,9.1/10,2009–2010,TV-14,Animation,Not time defined,Japan,Stars,1
3,Life,NaN,9.1/10,2009,TV-G,Documentary,Not time defined,United Kingdom,NaN,1
2,The Twilight Zone,NaN,9.1/10,1959–1964,Tous publics,Drama,Not time defined,United States,Stars,1

In [85]:
df_serie['public'].value_counts()

16+             7
Tous publics    5
TV-G            4
TV-14           3
7+              1
Name: public, dtype: int64